# FPSR Visualiser Metrics Tables

This notebook replicates and visualises the performance and algorithm evaluation tables from `fpsr_visualiser_metrics.md` using Python.

# Cross-Platform Algorithmic Throughput Analysis

This notebook analyzes cross-platform algorithmic throughput for various processing paradigms, computes cross-platform averages, and normalizes performance relative to **Legacy Paradigm A**.

## Table 1: Cross-Platform Throughput (FPS) for Various Processing Paradigms

In [25]:
import numpy as np
import pandas as pd

# Table 1: Cross-Platform Algorithmic Throughput (k/s)
# Figures taken strictly from the markdown table
platforms = ["VS Code Preview", "Chrome", "Firefox", "Android Chrome", "Android Firefox", "Android Comet"]

data = {
    "Algorithm": [
        "Legacy Paradigm A",
        "Legacy Paradigm B",
        "Stateless Perlin",
        "Stateless Worley",
        "FPS-R SM",
        "FPS-R TM",
        "FPS-R QS",
        "FPS-R BD (default 3 streams, blocksize 64)",
    ],
    "VS Code Preview": [2483, 2298, 870, 600, 1385, 1834, 872, 350],
    "Chrome": [2953, 2587, 1016, 691, 1747, 2135, 956, 390],
    "Firefox": [7710, 7300, 405, 226, 1092, 1838, 678, 328],
    "Android Chrome": [3010, 2724, 1076, 725, 1873, 2296, 1125, 423],
    "Android Firefox": [3550, 3360, 320.3, 183.8, 855.3, 1213, 435.5, 245.6],
    "Android Comet": [3188, 2583, 871.8, 590.1, 1537.1, 1923.4, 930.2, 308.3],
}

df_throughput = pd.DataFrame(data).set_index("Algorithm")

# Display Table 1 formatted with tildes and commas
table_1 = df_throughput.map(lambda x: f"~{x:,}")
table_1

                                           VS Code Preview  Chrome Firefox Android Chrome Android Firefox Android Comet
Algorithm
Legacy Paradigm A                                   ~2,483  ~2,953  ~7,710         ~3,010        ~3,550.0      ~3,188.0
Legacy Paradigm B                                   ~2,298  ~2,587  ~7,300         ~2,724        ~3,360.0      ~2,583.0
Stateless Perlin                                      ~870  ~1,016    ~405         ~1,076          ~320.3        ~871.8
Stateless Worley                                      ~600    ~691    ~226           ~725          ~183.8        ~590.1
FPS-R SM                                            ~1,385  ~1,747  ~1,092         ~1,873          ~855.3      ~1,537.1
FPS-R TM                                            ~1,834  ~2,135  ~1,838         ~2,296        ~1,213.0      ~1,923.4
FPS-R QS                                              ~872    ~956    ~678         ~1,125          ~435.5        ~930.2
FPS-R BD (default 3 streams, blocksize 64)            ~350    ~390    ~328           ~423          ~245.6        ~308.3

---
## Table 2: Average Throughput Across Platforms

In [26]:
# Table 2: Averaged Algorithmic Throughput (k/s)
# Calculated as the mean across the 4 platform columns
df_averaged = pd.DataFrame(
    {"Average Performance": df_throughput[platforms].mean(axis=1)}
)

# Standardize FPS-R BD label for summary tables
df_averaged.index = df_averaged.index.map(
    lambda name: "FPS-R BD" if "FPS-R BD" in name else name
)

# Format to 2 decimal places with tildes matching markdown
table_2 = df_averaged.map(lambda x: f"~{x:,.2f}")
table_2

                  Average Performance
Algorithm
Legacy Paradigm A           ~3,815.67
Legacy Paradigm B           ~3,475.33
Stateless Perlin              ~759.85
Stateless Worley              ~502.65
FPS-R SM                    ~1,414.90
FPS-R TM                    ~1,873.23
FPS-R QS                      ~832.78
FPS-R BD                      ~340.82

---
## Table 3: Normalized Performance Relative to Legacy Paradigm A

In [32]:
# Table 3: Performance Relative to Legacy Paradigm A Across Platforms
# R_{i, j} = performance(i, j) / Legacy_A(j)
legacy_a_baseline = df_throughput.loc["Legacy Paradigm A", platforms]
df_relative = df_throughput[platforms].div(legacy_a_baseline, axis=1)

# Compute the median ratio across the 4 platforms
df_relative["Median ratio"] = df_relative[platforms].median(axis=1)

# Simplify index label for FPS-R BD
df_relative.index = df_relative.index.map(
    lambda name: "FPS-R BD" if "FPS-R BD" in name else name
)


# Format each cell as "ratio / percentage%"
def format_ratio_pct(val):
    percent = val * 100
    percent_flag = False  # This variable is defined but not used; consider removing it if unnecessary
    return_str = f"{val:.3f}"
    if percent_flag:
        return_str += f" / {percent:.1f}%"
    return return_str


table_3 = df_relative.map(format_ratio_pct)
table_3

                  VS Code Preview Chrome Firefox Android Chrome Android Firefox Android Comet Median ratio
Algorithm
Legacy Paradigm A           1.000  1.000   1.000          1.000           1.000         1.000        1.000
Legacy Paradigm B           0.925  0.876   0.947          0.905           0.946         0.810        0.915
Stateless Perlin            0.350  0.344   0.053          0.357           0.090         0.273        0.309
Stateless Worley            0.242  0.234   0.029          0.241           0.052         0.185        0.210
FPS-R SM                    0.558  0.592   0.142          0.622           0.241         0.482        0.520
FPS-R TM                    0.739  0.723   0.238          0.763           0.342         0.603        0.663
FPS-R QS                    0.351  0.324   0.088          0.374           0.123         0.292        0.308
FPS-R BD                    0.141  0.132   0.043          0.141           0.069         0.097        0.114

In [35]:
# Display ranked format_ratio_pct for table 3
ranked_median_ratios = df_relative["Median ratio"].sort_values(ascending=False)
print(ranked_median_ratios)

# print ranked_median_ratios in a percentage format
print(ranked_median_ratios.apply(lambda x: f"{x:.1%}"))

Algorithm
Legacy Paradigm A    1.000000
Legacy Paradigm B    0.915238
FPS-R TM             0.663159
FPS-R SM             0.519972
Stateless Perlin     0.308760
FPS-R QS             0.307760
Stateless Worley     0.209550
FPS-R BD             0.114388
Name: Median ratio, dtype: float64
Algorithm
Legacy Paradigm A    100.0%
Legacy Paradigm B     91.5%
FPS-R TM              66.3%
FPS-R SM              52.0%
Stateless Perlin      30.9%
FPS-R QS              30.8%
Stateless Worley      21.0%
FPS-R BD              11.4%
Name: Median ratio, dtype: object

---
## Generate Markdown Table for Cross-Platform Throughput

In [33]:
# generate a markdown table for cross-platform throughput
# starting with headers:
#     | Algorithm | VS Code Preview | Chrome | Firefox | Android Chrome |
#     | :--- | ---: | ---: | ---: | ---: |

# generate the table with the formatted values
def df_to_markdown(df):
    headers = ["Algorithm"] + list(df.columns)
    alignments = [":---"] + ["---:"] * len(df.columns)
    header_line = "| " + " | ".join(headers) + " |"
    separator_line = "| " + " | ".join(alignments) + " |"
    rows = [
        "| " + " | ".join([str(idx)] + [str(val) for val in row]) + " |"
        for idx, row in df.iterrows()
    ]
    return "\n".join([header_line, separator_line] + rows)

print("### Table 1: Cross-Platform Throughput (FPS) for Various Processing Paradigms")
print(df_to_markdown(table_1))
print()

print("### Table 2: Average Throughput Across Platforms")
print(df_to_markdown(table_2))
print()

print("### Table 3: Normalized Performance Relative to Legacy Paradigm A")
print(df_to_markdown(table_3))

### Table 1: Cross-Platform Throughput (FPS) for Various Processing Paradigms
| Algorithm | VS Code Preview | Chrome | Firefox | Android Chrome | Android Firefox | Android Comet |
| :--- | ---: | ---: | ---: | ---: | ---: | ---: |
| Legacy Paradigm A | ~2,483 | ~2,953 | ~7,710 | ~3,010 | ~3,550.0 | ~3,188.0 |
| Legacy Paradigm B | ~2,298 | ~2,587 | ~7,300 | ~2,724 | ~3,360.0 | ~2,583.0 |
| Stateless Perlin | ~870 | ~1,016 | ~405 | ~1,076 | ~320.3 | ~871.8 |
| Stateless Worley | ~600 | ~691 | ~226 | ~725 | ~183.8 | ~590.1 |
| FPS-R SM | ~1,385 | ~1,747 | ~1,092 | ~1,873 | ~855.3 | ~1,537.1 |
| FPS-R TM | ~1,834 | ~2,135 | ~1,838 | ~2,296 | ~1,213.0 | ~1,923.4 |
| FPS-R QS | ~872 | ~956 | ~678 | ~1,125 | ~435.5 | ~930.2 |
| FPS-R BD (default 3 streams, blocksize 64) | ~350 | ~390 | ~328 | ~423 | ~245.6 | ~308.3 |

### Table 2: Average Throughput Across Platforms
| Algorithm | Average Performance |
| :--- | ---: |
| Legacy Paradigm A | ~3,815.67 |
| Legacy Paradigm B | ~3,475.33 |
| Stateless Perlin | ~759.85 |
| Stateless Worley | ~502.65 |
| FPS-R SM | ~1,414.90 |
| FPS-R TM | ~1,873.23 |
| FPS-R QS | ~832.78 |
| FPS-R BD | ~340.82 |

### Table 3: Normalized Performance Relative to Legacy Paradigm A
| Algorithm | VS Code Preview | Chrome | Firefox | Android Chrome | Android Firefox | Android Comet | Median ratio |
| :--- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Legacy Paradigm A | 1.000 | 1.000 | 1.000 | 1.000 | 1.000 | 1.000 | 1.000 |
| Legacy Paradigm B | 0.925 | 0.876 | 0.947 | 0.905 | 0.946 | 0.810 | 0.915 |
| Stateless Perlin | 0.350 | 0.344 | 0.053 | 0.357 | 0.090 | 0.273 | 0.309 |
| Stateless Worley | 0.242 | 0.234 | 0.029 | 0.241 | 0.052 | 0.185 | 0.210 |
| FPS-R SM | 0.558 | 0.592 | 0.142 | 0.622 | 0.241 | 0.482 | 0.520 |
| FPS-R TM | 0.739 | 0.723 | 0.238 | 0.763 | 0.342 | 0.603 | 0.663 |
| FPS-R QS | 0.351 | 0.324 | 0.088 | 0.374 | 0.123 | 0.292 | 0.308 |
| FPS-R BD | 0.141 | 0.132 | 0.043 | 0.141 | 0.069 | 0.097 | 0.114 |